# Generated by Django 6.0.7 on 2026-07-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FollowedArtist',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('genre_names', models.JSONField(blank=True, default=list)),
                ('url', models.TextField(blank=True, null=True)),
                ('artwork_template', models.TextField(blank=True, null=True)),
                ('artwork_color', models.CharField(blank=True, max_length=20, null=True)),
                ('known_release_ids', models.JSONField(blank=True, default=list)),
                ('latest_release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('total_release_count', models.IntegerField(default=0)),
                ('missing_release_count', models.IntegerField(default=0)),
                ('release_scope', models.CharField(default='all', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='album', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('album_id', models.CharField(blank=True, max_length=50, null=True)),
                ('song_id', models.CharField(blank=True, max_length=50, null=True)),
                ('playlist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('library_playlist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('album_title', models.CharField(default='Unknown Album', max_length=255)),
                ('artist', models.CharField(default='Unknown Artist', max_length=255)),
                ('artist_id', models.CharField(blank=True, max_length=50, null=True)),
                ('artwork_url', models.TextField(blank=True, null=True)),
                ('current_track', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_dir', models.TextField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('logs', models.TextField(blank=True, default='')),
            ],
        ),
    ]
